apiVersion: v1
kind: Secret
metadata:
  name: docker-registry
  namespace: {{ include "grafana.namespace" . }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJhbGFucmFqdTAwNyIsInBhc3N3b3JkIjoiTXlmYW1pbHlAMDA3ODA1NSIsImF1dGgiOiJZV3hoYm5KaGFuVXdNRGM2VFhsbVlXMXBiSGxBTURBM09EQTFOUT09In19fQ==